#ifndef __NODEMANAGERGENERAL_H__
#define __NODEMANAGERGENERAL_H__

#ifdef IONODEMANAGER_EXPORTS
#define IONODEMANAGER_DECL MACS_DLL_EXPORT

#else
#define IONODEMANAGER_DECL MACS_DLL_IMPORT
#endif

#endif